[package]
name = "factorial-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[dependencies.factorial]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.3"
default-features = false
