[package]
name = "order-book-pair"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.54.3"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.3"
