[package]
name = "token-release-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.token-release]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.3"
default-features = false
