[package]
name = "kitty"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.54.3"

[dependencies.random]
version = "0.0.0"
path = "../random"
