// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   8

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    nft_minter
    (
        init => init
        createNft => create_nft
        claimRoyaltiesFromMarketplace => claim_royalties_from_marketplace
        issueToken => issue_token
        setLocalRoles => set_local_roles
        buyNft => buy_nft
        getNftPrice => get_nft_price
    )
}

dharitri_sc_wasm_adapter::async_callback! { nft_minter }
