[package]
name = "token-release"
version = "0.0.1"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/token_release.rs"

[dependencies.dharitri-sc]
version = "0.54.3"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.3"
