[package]
name = "dcdt-transfer-with-fee-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dcdt-transfer-with-fee]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.3"
default-features = false
