[package]
name = "factory-meta"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[dependencies.order-book-factory]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.54.3"
default-features = false
