[package]
name = "crypto-bubbles"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[lib]
path = "src/crypto_bubbles.rs"

[dependencies.dharitri-sc]
version = "0.54.3"

[dev-dependencies.dharitri-sc-scenario]
version = "0.54.3"
